Cosmetic changes

diff --git a/packages/boot/initrd/src/sbin/pkg-backup b/packages/boot/initrd/src/sbin/pkg-backup
--- a/packages/boot/initrd/src/sbin/pkg-backup
+++ b/packages/boot/initrd/src/sbin/pkg-backup
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# Rebuild a package tarball to the boot media
+# Rebuilds a package tarball to the boot media
 
 . /lib/libscript
 
@@ -8,14 +8,14 @@ help() {
 	echo "\
 Usage: $(basename "$0") <package>
 
-Rebuild a package tarball to the boot media." >&2
+$DESCRIPTION." >&2
 	exit 1
 }
 
 [ "$#" != 1 -o "$1" = "-h" -o "$1" = "--help" ] && help
 
 if [ ! -f "/var/lib/lrpkg/$1.list" ]; then
-	echo "Package $1 not found." >&2
+	echo "Package '$1' not found." >&2
 	exit 1
 fi
 
